### PR TITLE
docs: Add missing step for extension installation when restarting Polarion and clearify sections element a bit.

### PR DESCRIPTION
**Pull request by martijndegouw**
I've added the information I missed when following the quickstart guide.

### CODE REVIEW

**Comment by grigoriev** [comment]
@martijndegouw could you please change your commit message to "docs: add missing step for extension installation when restarting Polarion and clearify sections element a bit" ? we are using conventional commits like [here](https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/blob/main/CONTRIBUTING.md#commit-message-guidelines) described.

**Review by grigoriev — APPROVED** [review]

**Review by ariwk — APPROVED** [review]

**Comment by ariwk** [comment]
the commit https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/pull/233/commits/7b910d01d5fbc715df351bb9844faeb81bd004dc was not signed and we cannot merge this PR due to the base branch requirements

@martijndegouw please refer to https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/blob/main/CONTRIBUTING.md#submitting-changes

`git commit -a -S` --> please always use '-S' parameter to sign your commits

You are owner of your code changes based on our licensing model but only when your commits are signed:
- https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/blob/main/LICENSES/SBB.txt 
- https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/blob/main/LICENSES/DCO.txt

**Comment by ariwk** [comment]
@martijndegouw I meant "git commit -S" not "git commit -s". "-S" means --gpg-sign

**Comment by martijndegouw** [comment]
> @martijndegouw I meant "git commit -S" not "git commit -s". "-S" means --gpg-sign

The commit is gpg signed.

**Pull request merged**
